export default [
    "Aaland Islands",
    "Albania",
    "Andorra",
    "Anguilla",
    "Aruba",
    "Austria",
    "Azerbaijan",
    "Belgium",
    "Bermuda",
    "Bosnia and Herzegowina",
    "Bouvet Island",
    "British Indian Ocean Territory",
    "Bulgaria",
    "Cayman Islands",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Falkland Islands (Malvinas)",
    "Faroe Islands",
    "Finland",
    "France",
    "France, Metropolitan",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Germany",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Guadeloupe",
    "Guernsey",
    "Heard and Mc Donald Islands",
    "Hungary",
    "Iceland",
    "Ireland",
    "Isle of Man",
    "Italy",
    "Jersey",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia, The Former Yugoslav Republic of",
    "Malta",
    "Martinique",
    "Mayotte",
    "Moldova, Republic of",
    "Monaco",
    "Montserrat",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia",
    "Niue",
    "Northern Ireland",
    "Norway",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Reunion",
    "Romania",
    "San Marino",
    "Scotland",
    "Slovakia (Slovak Republic)",
    "Slovenia",
    "South Georgia and the South Sandwich Islands",
    "Spain",
    "St. Helena",
    "St. Pierre and Miquelon",
    "Svalbard and Jan Mayen Islands",
    "Sweden",
    "Switzerland",
    "Turkey",
    "United Kingdom",
    "Vatican City State (Holy See)",
    "Virgin Islands (British)",
    "Wales",
    "Wallis and Futuna Islands"
];
